### ISSUE TITLE
[Bug or wrong usage?] RuntimeError: float unrepresentable in integer range

### ISSUE THREAD

**Issue by igrep** [tweag/asterius#105]
# How to reproduce

## Minimum hs and mjs file to reproduce

ahcbug.hs:

```haskell
import           Asterius.Types        (JSString (JSString), JSVal (JSVal))

foreign export javascript "bug" bug :: JSString -> JSString

bug :: JSString -> JSString
bug = id

main :: IO ()
main = return ()
```

ahcbug.mjs:

```js
import {module} from "./ahcbug.wasm.mjs";
import * as ahcbug from "./ahcbug.lib.mjs";
import {encodeUTF8, decodeUTF8} from "./rts.utf8.mjs"

module.then(m => ahcbug.newInstance(m)).then(i => {
try {
i.wasmInstance.exports.hs_init();
console.log(decodeUTF8(i.wasmInstance.exports.bug(encodeUTF8("1"))));
} catch (err) {
console.log(i.stdio.stdout());
throw err;
}
console.log(i.stdio.stdout());
});
```

## Build command

```
sudo docker run -it -v `pwd`:/mirror terrorjack/asterius:latest bash -c 'cd /mirror/ ; ahc-link --export-function bug --input-hs ahcbug.hs --input-mjs ahcbug.mjs --browser' && sudo chown -R "$USER" *
```

## Result

Console output when accessing via Google Chrome 73.0.3683.103 (Official Build) (64bit) to ahcbug.html:

```
ahcbug.mjs:10 
wasm-00021f12-68:3 Uncaught (in promise) RuntimeError: float unrepresentable in integer range
    at wasm-function[68]:3
    at http://localhost:21172/ahcbug.mjs:8:47
```

![image](https://user-images.githubusercontent.com/227057/55922220-2ed44580-5c3b-11e9-96af-9a583478f821.png)

**Comment by TerrorJack** [comment]
It should be a wrong usage (but due to insufficient documentation).

The `foreign export`ed Haskell functions are indeed available in `i.wasmInstance.exports`, and can be called in JavaScript, *provided the parameters and return value are simple integral/floating-point types*.

So what about `JS*` types? Keep in mind about two facts:

* WebAssembly doesn't allow any JavaScript reference to pass through JavaScript/WebAssembly boundary. Therefore `i.wasmInstance.exports(some_js_value)` won't work.
* We can, however, pass integers instead. Store the JavaScript value somewhere, retrieve an integer as a handle, then pass the handle into WebAssembly(Haskell). In Haskell the handle type is `JSVal`, which is a `newtype` of `StablePtr` at the moment.

So in order to pass `JS*` into Haskell, we need to call `i.newJSVal(some_js_value)` to get the handle, and pass the handle to the exported function. Likewise, when getting such a handle from Haskell, use `i.getJSVal(handle)` to obtain the real JavaScript value.

Sorry about the confusion though. Can you give it a try if above explanation works for you?

**Comment by igrep** [comment]
I'm sorry too. I misunderstood the restriction of wasm.
Anyway, wrapping with `i.newJSVal` and `i.getJSVal`  like below successfully runs without any error!
Thank you very much! 😸 

```javascript
...
console.log(decodeUTF8(i.getJSVal(i.wasmInstance.exports.bug(i.newJSVal(encodeUTF8("1"))))));
...
```

**Comment by igrep** [comment]
But let me ask you one more! 🙏 
 how can I modify the `JSVal` by Haskell code?

I tried to rewrite the `bug` function like below, but the returned value is still `"1"`.
I bet I still miss something...

```haskell
bug :: JSString -> JSString
bug = toJSString . ('a' :) . fromJSString
```

**Comment by TerrorJack** [comment]
Now that's indeed a bug. In the Haskell world, no special operations about `StablePtr` should be required.

Note that there's a [`teletype`](https://github.com/tweag/asterius/blob/master/asterius/test/teletype/teletype.hs) unit test which involves string conversions between js/hs, and the [CI log](https://circleci.com/gh/tweag/asterius/3197) shows expected behavior. The string conversion logic was all called from a `main` function, so it's possible calling it from exported function instead triggered some unexpected bug. I'll need to find some time to investigate it though. Thanks for catching this one :)

**Comment by TerrorJack** [comment]
Closing this one for now due to inactivity; the rts interface for passing `JSVal`s across hs/wasm has changed, I've taken note for this example and will see if the problem persists in updated version.

**Comment by catrujillo91** [comment]
> It should be a wrong usage (but due to insufficient documentation).
> 
> The `foreign export`ed Haskell functions are indeed available in `i.wasmInstance.exports`, and can be called in JavaScript, _provided the parameters and return value are simple integral/floating-point types_.
> 
> So what about `JS*` types? Keep in mind about two facts:
> 
> * WebAssembly doesn't allow any JavaScript reference to pass through JavaScript/WebAssembly boundary. Therefore `i.wasmInstance.exports.f(some_js_value)` won't work.
> * We can, however, pass integers instead. Store the JavaScript value somewhere, retrieve an integer as a handle, then pass the handle into WebAssembly(Haskell). In Haskell the handle type is `JSVal`, which is a `newtype` of `StablePtr` at the moment.
> 
> So in order to pass `JS*` into Haskell, we need to call `i.newJSVal(some_js_value)` to get the handle, and pass the handle to the exported function. Likewise, when getting such a handle from Haskell, use `i.getJSVal(handle)` to obtain the real JavaScript value.
> 
> Sorry about the confusion though. Can you give it a try if above explanation works for you?

Hey mate, when i package my ue4 project to html5 and open in on google chrome i get this error:

Array.ASM_CONSTS (blob:http://localhost:8000/16ca2c93-cf14-4df6-a97e-051c5ff1ea1a:1179:18) at emscripten_asm_const_i (blob:http://localhost:8000/16ca2c93-cf14-4df6-a97e-051c5ff1ea1a:1303:25) at ZN17FOpenGLDynamicRHI38RHICreateBoundShaderState_OnThisThreadEP21FRHIVertexDeclarationP16FRHIVertexShaderP14FRHIHullShaderP16FRHIDomainShaderP15FRHIPixelShaderP18FRHIGeometryShaderb (wasm-function[28677]:0x109b2c6) at ZN17FOpenGLDynamicRHI34RHICreateBoundShaderState_internalEP21FRHIVertexDeclarationP16FRHIVertexShaderP14FRHIHullShaderP16FRHIDomainShaderP15FRHIPixelShaderP18FRHIGeometryShaderb (wasm-function[28062]:0x104c64b) at ZN17FOpenGLDynamicRHI27RHISetGraphicsPipelineStateEP25FRHIGraphicsPipelineState (wasm-function[28010]:0x104b91c) at ZThn16_N17FOpenGLDynamicRHI27RHISetGraphicsPipelineStateEP25FRHIGraphicsPipelineState (wasm-function[28027]:0x104bde9) at ZN11FRHICommandI35FRHICommandSetGraphicsPipelineState45FRHICommandSetGraphicsPipelineStateString1296E18ExecuteAndDestructER19FRHICommandListBaseR27FRHICommandListDebugContext (wasm-function[29329]:0x110faf0) at ZN23FRHICommandListExecutor22ExecuteInner_DoExecuteER19FRHICommandListBase (wasm-function[29106]:0x10d614a) at ZN21FExecuteRHIThreadTask6DoTaskEN13ENamedThreads4TypeERK12TRefCountPtrI11FGraphEventE (wasm-function[29111]:0x10d6a1a) at _ZN10TGraphTaskI21FExecuteRHIThreadTaskE11ExecuteTaskER6TArrayIP14FBaseGraphTask22TSizedDefaultAllocatorILi32EEEN13ENamedThreads4TypeE (wasm-function[29110]:0x10d66a3) Uncaught RuntimeError: float unrepresentable in integer range Uncaught RuntimeError: float unrepresentable in integer range Uncaught RuntimeError: float unrepresentable in integer range Uncaught RuntimeError: float unrepresentable in integer range Uncaught RuntimeError: float unrepresentable in integer range


Can you please help me? Im not a programer, Im a begginer in unreal. And i see this big error message but i dont understand a thing :( How can i fix it (its like another language for me)
