### ISSUE TITLE
Extra "\n" emitted by asterius

### ISSUE THREAD

**Issue by bollu** [tweag/asterius#162]
Consider the sample code:

```
data X = X deriving(Show)

main :: IO ()
main = print X
```

##### GHC output:
```
╭─bollu@strangeattractor ~/work/asterius ‹june-2-pass-numrun012-on-top-of-cgrun044*› 
╰─$ ghc foo.hs && ./foo
Linking foo ...
X
╭─bollu@strangeattractor ~/work/asterius ‹june-2-pass-numrun012-on-top-of-cgrun044*› 
╰─$ 
```

##### AHC output:
```
╭─bollu@strangeattractor ~/work/asterius ‹june-2-pass-numrun012-on-top-of-cgrun044*› 
╰─$ stack exec ahc-link -- --input-hs foo.hs && echo "---" && node  --experimental-wasm-return-call --experimental-modules  foo.mjs        
[INFO] Compiling foo.hs to WebAssembly
[INFO] Converting linked IR to wasm-toolkit IR
[INFO] Writing WebAssembly binary to "./foo.wasm"
[INFO] Writing JavaScript runtime constants to "./rts.constants.mjs"
[INFO] Writing JavaScript runtime modules to "."
[INFO] Writing JavaScript loader module to "./foo.wasm.mjs"
[INFO] Writing JavaScript lib module to "./foo.lib.mjs"
[INFO] Writing JavaScript entry module to "./foo.mjs"
---
(node:15603) ExperimentalWarning: The ESM module loader is experimental.
X

╭─bollu@strangeattractor ~/work/asterius ‹june-2-pass-numrun012-on-top-of-cgrun044*› 
```

Clearly, there's an extra newline emitted by asterius.

This causes us to fail `testsuite/numeric/T9407`

**Comment by TerrorJack** [comment]
The relevant logic to generate the entry script `foo.mjs` is in `Asterius.Main.genDefEntry`. By default, after initializing the instance and calling `hs_init`/`main`, out `stdout` cache is populated by some output sent from haskell, and we output the `stdout` cache via `console.log`, which itself adds an extra `\n`.

However, the extra `\n` added by `console.log` there should be irrelevant to the failure in `T9407`, since in `ghc-testsuite`, we use `inline-js-core` to fetch `stdout` as a `ByteString` directly and perform the comparison, thus no extra `\n` is present in that case.
