### ISSUE TITLE
Correctly implement Unicode toTitle

### ISSUE THREAD

**Issue by hsyl20** [tweag/asterius#274]
``u_towtitle`` is currently implemented using ``u_towupper`` in ``asterius/rts/rts.unicode.mjs`` which is not totally correct (AFAIK).

**Comment by curiousleo** [comment]
Title case differs from upper case for certain ligatures: https://www.compart.com/en/unicode/category/Lt. The `WCsubst.c` in `base` file defining, amongst other things, `u_towtitle`, is generated:
```
WCsubst.c is generated with:

   sh ubconfc < UnicodeData.txt > WCsubst.c

where UnicodeData.txt came from

   https://www.unicode.org/Public/12.0.0/ucd/UnicodeData-12.0.0d4.txt
```
https://gitlab.haskell.org/ghc/ghc/blob/9c11f8171a9aebec4b4d19e5eac4140f40c28542/libraries/base/cbits/README.Unicode

This seems like a sensible approach to me, making it easy to update this as the Unicode spec changes. Note that the above link, strangely enough, does not work. The most up to date file for Unicode 12.0.0 appears to be https://www.unicode.org/Public/12.0.0/ucd/UnicodeData.txt, and the most up to date version overall appears to be https://www.unicode.org/Public/13.0.0/ucd/UnicodeData-13.0.0d6.txt at the moment.

I think it would be worth investigating how difficult it would be to adapt https://gitlab.haskell.org/ghc/ghc/blob/9c11f8171a9aebec4b4d19e5eac4140f40c28542/libraries/base/cbits/ubconfc to generate JavaScript instead of C.

**Comment by TerrorJack** [comment]
Makes sense. And would be nice to rewrite the C generator into a Haskell script for ease of reviewing & refactoring.

**Comment by curiousleo** [comment]
This comment also seems relevant: https://github.com/tweag/asterius/blob/b1b8fed316f0c3a2c9734c46f31af9e4a8fba2e5/asterius/src/Asterius/Builtins.hs#L1475-L1479

**Comment by curiousleo** [comment]
Quick update - I'm close to being able to generate a version of `rts.unicode.mjs` that is as correct as the Unicode handling in the GHC base library. I still need to figure out how to test and integrate it properly though.

**Comment by curiousleo** [comment]
Using a similar approach as is used to "compress" character information in the GHC script, I am now able to generate this file: https://github.com/tweag/asterius/blob/e7d50de0e11c796ebc93576ee9c8b71a7987e5c0/asterius/rts/rts.unicode2.mjs - it's reasonably compact and should be quite efficient given that everything is represented as typed arrays. I have yet to benchmark it though.
