### ISSUE TITLE
Improve CI setup

### ISSUE THREAD

**Issue by mrkkrp** [tweag/asterius#3]
CI setup is a bit manual and ad-hoc currently. To improve the situation the following steps are proposed:

* Asterius currently needs GHC compiled with a custom config. I created a new repo here: https://github.com/tweag/asterius-ghc-gen.
* I'll enable CircleCI for it and make it run periodically. It'll clone GHC, but necessary config in place and compile it.
* A bindist will be produced and collected by `ghc-artifact-collector` that we use with vanilla GHC already. The job will be called `asterius-x86_64-linux`.
* In Asterius CI we download the latest bindist created this way and use it.

**Comment by mboes** [comment]
Further nice-to-have requirements (may or may not be workable):

* asterius should remain forkable. If CI relies on custom infra, then it's no longer forkable (any forker would need to replicate this infra themselves). This implies that CircleCI cache better than an S3 bucket that would be world readable but only writable from Tweag workspace.

**Comment by TerrorJack** [comment]
@mboes I'd like to clarify a bit. I decided to base asterius on ghc head and follow upstream changes, because that was one of a pain spot when using ghcjs in the past (having several branches for different ghc releases, requiring extra effort to make it work once a new release is out, etc). That's the reason for routinely bumping ghc revisions, because for small breaking changes in ghc master (which happens a lot!) it's relatively easy to follow, but for point releases it will be a lot of work.

Furthermore, right now it's already deterministic: every revision of asterius already pins with one exact commit of ghc, so even if a regression is introduced it won't be much of a problem to bisect and track the breaking commit.

Also, the current CI setup and the new one @mrkkrp is working on both don't trigger a new build for ghc with every asterius commit. 

I'm okay with introducing a ghc tree as submodule and using that, but automatic (or at least, semi-automatic) bumping of ghc revisions is not nonsense. I hope I've explained the rationale.

**Comment by mboes** [comment]
To be clear, I'm not arguing to only use GHC releases. Using *a* commit from GHC HEAD is fine, so long as we're not *automatically* switching to whatever is *the latest* commit. This is no different than for any other project dependency. Dependencies need to be vetted, and updates to dependencies need to be vetted too.

> Also, the current CI setup and the new one @mrkkrp is working on both don't trigger a new build for ghc with every asterius commit.

I think they should (but thanks to caching this won't be noticeable).

**Comment by mrkkrp** [comment]
Opened #7 for CircleCI part.

**Comment by TerrorJack** [comment]
We are building ghc bindists on separate branches then using them for CI in `master` and other `wip-*` branches. The advantage of building bindists instead of utilizing CI caches is improved end-user experience: people do not need to set up a building environment on their end, rather they'll just use a plain `stack build` and it mostly works out of the box.
