### ISSUE TITLE
TODOMVC fails on Safari

### ISSUE THREAD

**Issue by LeanderK** [tweag/asterius#401]
I can't interact with it, not sure if safari is not supported yet or if it's an regression. I have the following errors in my console:

```
[Error] Unhandled Promise Rejection: TypeError: first argument must be an ArrayBufferView or an ArrayBuffer (evaluating 'WebAssembly.instantiate(req.bufferSource, importObject)')
	(anonymous function) (todomvc.js:975)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJob
[Error] Failed to load resource: the server responded with a status of 404 () (learn.json, line 0)
```

For the second error it wants to load: https://www.tweag.io/wasm-todomvc/learn.json (which results in a `404`)

**Comment by TerrorJack** [comment]
Thanks for reporting. I managed to reproduce the same issue with midori, will investigate some time.

**Comment by TerrorJack** [comment]
Since I don't have a darwin device with safari, I used [Epiphany Technology Preview](https://webkit.org/downloads/) on linux, version number `3.35.2-32-g6d83ac8f4`. Two problems are discovered:

* `WebAssembly.instantiateStreaming` is not supported. It works with Chromium and Firefox and we assumed it to be present in all browser targets.
* `BigInt` is not supported.

The first problem can be easily worked around, but not the second one, since `BigInt` is used extensively throughout our runtime. Judging from the Test262 [report](https://test262.report/features/BigInt) about `BigInt`, only 5% of tests pass with `JavaScriptCore`, so the conclusion is: our generated code doesn't work with safari now, and will remain so for some more time. This is an upstream issue.

**Comment by LeanderK** [comment]
so, assuming safari implements BigInt, the demo should work? After some googling it seems that apple is working on BigInt (it may already be available in the tech-preview? Some functionality related to BigInt is mentioned)

**Comment by TerrorJack** [comment]
Yes it should. And here's a link to the webkit bigint tracking issue: https://bugs.webkit.org/show_bug.cgi?id=179001

**Comment by LeanderK** [comment]
Sry to revisit this old ticket, but using a polyfil won't cut it, right?

**Comment by TerrorJack** [comment]
@LeanderK  In theory a polyfill like https://github.com/GoogleChromeLabs/jsbi may work, provided it supports all the `BigInt` operations we use in the runtime for now. I haven't opened a ticket or scheduled the work to add a `jsbi` compat layer, since it's a whole lot of work (mainly involved in the runtime) and of limited benefit.

In case someone is interested to roll their sleeves and do a `BigInt` compat mode for browsers without native `BigInt`, I can offer more detailed explanation of how the runtime uses `BigInt` and what to do to switch away.

**Comment by LeanderK** [comment]
I might be interested to work on this since safari is my default browser (and it would enable asterius on iOS). But only out of interest, I also don't have the time right now anyway. Maybe next month!

**Comment by typedrat** [comment]
I possess quite a bit of free time right now and this is the only thing blocking Asterius from being quite useful to me. I'll take a look at this, especially if @TerrorJack can get me the info they mentioned. 🙂

**Comment by typedrat** [comment]
@TerrorJack, I know it's been a busy time for everyone, but I'd really love to get that info!

**Comment by gkaracha** [comment]
@typedrat I had a quick look with @TerrorJack and I opened a feature request with more explicit info about how to address this issue. Lemme know if everything is clear or if I can help in any way! :slightly_smiling_face:

**Comment by LeanderK** [comment]
new issue for new error: #837
