### ISSUE TITLE
Fix Cmm narrowing operators for `Int8#`/`Word8#`

### ISSUE THREAD

**Issue by TerrorJack** [tweag/asterius#47]
Note: `Int8#`/`Word8#` isn't widely used in the boot libs yet, so this is a medium-priority issue and will be checked only after #44 

Cmm has narrowing operators `MO_SS_Conv`/`MO_UU_Conv` which narrows a 64-bit `Int#`/`Word#` to 32-bit or lower, while still using a 64-bit local/global register for storage. The codegen already handles 64-to-32 narrowing, but the newly added `Int8#`/`Word8#` requires more aggressive 64-to-8 narrowing. Note that wasm doesn't have native opcodes for this purpose, so we need a pair of store/load opcodes here. When we later `Worker`ify the runtime, we also need extra care not to introduce a race condition since it involves a pinned temporary memory region.

**Comment by bollu** [comment]
Oh, I see, so you wish to store / load from a slot of memory from which we can then `load` an `i8` section using the wasm `load` instruction?

**Comment by TerrorJack** [comment]
Indeed. In `Asterius.Builtins.rtsAsteriusModule` we can put a new word-sized static variable, and perform store/load there to implement the narrowing operation which preserves lower 8 or 16 bits.

**Comment by bollu** [comment]
So, concretely:

- we create a new linear memory in global scope where we can `load` / `store` into.
- When we encounter `MO_UU_Conv` for, say `32` to `8`, we store the `32` bit integer into the linear memory, and then use `load` to load the `8` bottom bits, correct? And we `load` into a new variable of what size? 32? 64? (these are the only two choices we have, since wasm only supports 32/64 bit?)

**Comment by TerrorJack** [comment]
We represent any cmm type with less than 32bits with i32, so we load into i32 in this case.

**Comment by TerrorJack** [comment]
Fixed by #114.
