### ISSUE TITLE
Optimize the gc-sections pass

### ISSUE THREAD

**Issue by TerrorJack** [tweag/asterius#568]
**Is your feature request related to a problem? Please describe.**
The gc-sections pass contributes to no less than 1/3 of total run time in `ahc-ld` according to preliminary profiling analysis. In this pass, the majority of time is spent in `collectEntitySymbols`, which traverses the entity definition with the `Data` instance and collects `EntitySymbol`s.

**Describe the solution you'd like**
For each entity (data segment or function), we should already know the outreaching symbol set at compile-time. This information should also be encoded into the object files. At link-time, when deserializing each entity, we also deserialize its outreaching symbol set and construct an in-memory directed graph. There'll then be no need to run `collectEntitySymbols` at link-time.

**Comment by gkaracha** [comment]
In short, the desired solution does no longer store only `AsteriusModule`s in object files. Since `AsteriusModule` is quite central in Asterius' codebase, it's best if we do the transition gradually. After discussing this with @TerrorJack, the current approach to addressing this issue is the following:

__The plan__

1. Define a separate type (`AsteriusCachedModule`), which includes `AsteriusModule` but also the symbol reachability information we have computed at compile-time.
2. Use this object type when serializing/deserializing things, but initially leave the reachability information as null.
3. Move on to running `collectEntitySymbols` at compile-time to populate the actual symbol reachability info.
4. Use the cached information in the GC sections pass (`Asterius.Passes.GCSections.gcSections`) and avoid running `collectEntitySymbol` at link-time.
