### ISSUE TITLE
this.exports.stg_returnToSchedNotPaused is not a function

### ISSUE THREAD

**Issue by mikesol** [tweag/asterius#623]
**Describe the bug**
When following the documentation for using `ahc-cabal` to build an executable that is then built using `ahc-dist` in `--browser --bundle` mode, the following error comes up:

```bash
TypeError
this.exports.stg_returnToSchedNotPaused is not a function
```

The problem does not arise when using `ahc-link`.

**To Reproduce**

Build the `todomvc.hs` test using `ahc-cabal`.

**Expected behavior**

The flow with `ahc-cabal` and `ahs-dist` produces the same successful result as using `ahc-link`.

**Environment**
 - Windows 10 using the docker container but serving a static html file from an express server running on windows.
- Using the brave browser

--

Thanks for your awesome project and thanks in advance for your help! If you can't reproduce it using the `todomvc.hs` as described above, please let me know.

**Comment by mikesol** [comment]
As a follow up, here is a minimal example to produce the bug: https://github.com/mikesol/ahc-cabal-bug-minimal-example

**Comment by janakg** [comment]
We are also facing this same issue after building the duckling project to wasm.

**Comment by TerrorJack** [comment]
Ah, I see what the problem is. The `-threaded` option is used when linking the executables, and then `ahc` is trying to link `libHSrts_thr.a`, but we only create `libHSrts.a` when booting. Thus the `rts` package isn't linked into wasm.

An immediate workaround is avoiding `-threaded` in executable targets. But this is surely a bug and we'll soon fix the `-threaded` flag support (although it'll still link to the same non-threaded `rts`). Thanks for reporting :)
