### ISSUE TITLE
Export static dependencies to the package repositoory

### ISSUE THREAD

**Issue by majkrzak** [tweag/asterius#76]
During compilation, bunch of redundant static `rts` are generated. They can be exported to some module repository like `npm` for node target, so only necessary files will be created. Either use local `rts` or remote one might be controlled with some flag. Currently I have no idea how browser target should be handled in that case.

**Comment by TerrorJack** [comment]
Do you mean collecting all runtime code into an npm package?

**Comment by majkrzak** [comment]
Yes and something similar for the browser env.

**Comment by TerrorJack** [comment]
Closing this one for now due to inactivity.

We're still using ES6 module files without a `package.json` for now, since this configuration works in both node and browsers without needing transpilation. It's still possible for us to introduce npm dependencies and mandatory transpilation some time from now though.
